### ISSUE TITLE
auto-require registration

### ISSUE THREAD

**Issue by jaredly** [nasser/clojurescript-npm#1]
It would be super cool to just put `require('clojurescript/register')`  and it would hook into the `require` logic such that you could do `require('./my/file.clj')` and it would just work :D 
Coffeescript has this, and babel does too, and it makes it really nice to get up and running.

**Comment by nasser** [comment]
Ah that's really nice. Yes, `require` integration is going to be an interesting path to walk, and clojurescript and javascript both have their own notion of how that should work.

**Comment by nasser** [comment]
Added in 79517127

**Comment by jaredly** [comment]
So cool!
